# local-chat-radius: radius of local chat channel (in blocks)
# default-channel: default chat channel that new users will join
# default-colour: default new channel colour
# announce-timeouts: announce timeouts to the entire server?
# chat-format: the format chat will be printed in
# emote-format: the format emotes will be printed in
# 	** for the above 2, use the following substitutions:
#		%channel	the players channel
#		%prefix		the players prefix (from PermissionsEx)
#		%suffix		the players suffix (from PermissionsEx)
#		%player		the players name
#		%message	the message
# spam:
#     limit: number of messages sent
#     period: within the given time period
# hard channels
#	channel name:
#		colour: <colour name>
#		alias: <alias> (for example, alias = "g", type "/g" to switch to channel G
#		local: <true/false> (optional)
#		broadcast: <true/false> (optional)
#		permission: <permission node> permission node to get into the channel (optional)
#						final permission string will be: "mcnsachat2.channel.<permission node>"
#		listeners: <permission node> permission node to automatically listen in on the channel (optional)
#						final permission string will be: "mcnsachat2.listen.<permission node>"
local-chat-radius: 200
default-channel: G
default-colour: grey
announce-timeouts: true
chat-format: "<%channel&f> [%prefix%suffix&f] %player: &7%message"
emote-format: "<%channel&f> [%prefix%suffix&f] *%player &7%message"
spam:
  limit: 5
  period: 3
hard-channels:
  G:
    colour: grey
    alias: g
  L:
    colour: pink
    alias: lo
    local: true
  Broadcast:
    colour: purple
    alias: bc
    permission: broadcast
    broadcast: true
  MOD:
    colour: purple
    alias: m
    permission: mod
    listeners: mod
  ADMIN:
    colour: green
    alias: a
    permission: admin
    listeners: admin